export const endpoints = {
  login: "/api/auth/login",
  refresh: "/api/auth/refresh",
  logout: "/api/auth/logout",
  meAthletes: "/api/me/athletes",
  meProfile: "/api/me/profile",
  meGroups: "/api/me/groups",
  meTrainings: "/api/me/trainings",
  meAttendance: "/api/me/attendance",
  mePayments: "/api/me/payments",
  meAnnouncements: "/api/me/announcements",
  meAnnouncementsUnreadCount: "/api/me/announcements/unread-count",
  meAnnouncementsRead: "/api/me/announcements/read",
  meAthleteReports: "/api/me/athlete-reports",
  schoolAnnouncements: "/api/school/announcements",
  schoolAnnouncement: (announcementId: string) => `/api/school/announcements/${announcementId}`,
  schoolGroups: "/api/school/groups",
  schoolAthletes: "/api/school/athletes",
  schoolGroup: (groupId: string) => `/api/school/groups/${groupId}`,
  schoolGroupAthletes: (groupId: string) => `/api/school/groups/${groupId}/athletes`,
  schoolGroupAthlete: (groupId: string, athleteProfileId: string) => `/api/school/groups/${groupId}/athletes/${athleteProfileId}`,
  schoolTrainings: "/api/school/trainings",
  schoolTraining: (trainingId: string) => `/api/school/trainings/${trainingId}`,
  schoolPayments: "/api/school/payments",
  schoolPaymentSettings: "/api/school/payment-settings",
  schoolAthleteFee: (athleteProfileId: string) => `/api/school/athletes/${athleteProfileId}/fee`,
  schoolAthletePayment: (athleteProfileId: string, year: number, month: number) =>
    `/api/school/athletes/${athleteProfileId}/payments/${year}/${month}`,
  coachSummary: "/api/mobile/coach/summary",
  coachGroups: "/api/mobile/coach/groups",
  coachAthletes: "/api/mobile/coach/athletes",
  coachAthlete: (athleteProfileId: string) => `/api/mobile/coach/athletes/${athleteProfileId}`,
  coachAthleteReports: (athleteProfileId: string) => `/api/mobile/coach/athletes/${athleteProfileId}/reports`,
  coachTrainings: "/api/mobile/coach/trainings",
  coachAttendanceRoster: (trainingId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance-roster`,
  coachAttendance: (trainingId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance`,
  coachAttendanceItem: (trainingId: string, athleteProfileId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance/${athleteProfileId}`
} as const;
