export const endpoints = {
  loginSchools: "/api/auth/schools",
  login: "/api/auth/login",
  refresh: "/api/auth/refresh",
  logout: "/api/auth/logout",
  meProfile: "/api/me/profile",
  meGroups: "/api/me/groups",
  meTrainings: "/api/me/trainings",
  meAttendance: "/api/me/attendance",
  mePayments: "/api/me/payments",
  meAthleteReports: "/api/me/athlete-reports",
  schoolGroups: "/api/school/groups",
  schoolGroup: (groupId: string) => `/api/school/groups/${groupId}`,
  schoolGroupAthletes: (groupId: string) => `/api/school/groups/${groupId}/athletes`,
  schoolGroupAthlete: (groupId: string, athleteProfileId: string) => `/api/school/groups/${groupId}/athletes/${athleteProfileId}`,
  schoolTrainings: "/api/school/trainings",
  coachSummary: "/api/mobile/coach/summary",
  coachGroups: "/api/mobile/coach/groups",
  coachAthletes: "/api/mobile/coach/athletes",
  coachAthlete: (athleteProfileId: string) => `/api/mobile/coach/athletes/${athleteProfileId}`,
  coachAthleteReports: (athleteProfileId: string) => `/api/mobile/coach/athletes/${athleteProfileId}/reports`,
  coachTrainings: "/api/mobile/coach/trainings",
  coachAttendanceRoster: (trainingId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance-roster`,
  coachAttendance: (trainingId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance`,
  coachAttendanceItem: (trainingId: string, athleteProfileId: string) => `/api/mobile/coach/trainings/${trainingId}/attendance/${athleteProfileId}`
} as const;
