export const endpoints = {
  health: "/api/health",
  bootstrapPlatformOwner: "/api/bootstrap/platform-owner",
  login: "/api/auth/login",
  refresh: "/api/auth/refresh",
  logout: "/api/auth/logout",
  changePassword: "/api/auth/change-password",
  platformSchools: "/api/platform/schools",
  platformSchool: (schoolId: string) => `/api/platform/schools/${schoolId}`,
  platformSchoolAdmins: (schoolId: string) => `/api/platform/schools/${schoolId}/admins`,
  schoolUsers: "/api/school/users",
  schoolCoaches: "/api/school/coaches",
  schoolAthletes: "/api/school/athletes",
  athleteApplications: "/api/applications/athletes",
  schoolAthleteApplications: "/api/school/athlete-applications",
  approveAthleteApplication: (applicationId: string) => `/api/school/athlete-applications/${applicationId}/approve`,
  rejectAthleteApplication: (applicationId: string) => `/api/school/athlete-applications/${applicationId}/reject`,
  schoolGroups: "/api/school/groups",
  schoolGroup: (groupId: string) => `/api/school/groups/${groupId}`,
  groupAthlete: (groupId: string, athleteProfileId: string) => `/api/school/groups/${groupId}/athletes/${athleteProfileId}`,
  schoolTrainings: "/api/school/trainings",
  groupTrainings: (groupId: string) => `/api/school/groups/${groupId}/trainings`,
  trainingAttendance: (trainingId: string) => `/api/school/trainings/${trainingId}/attendance`,
  trainingAthleteAttendance: (trainingId: string, athleteProfileId: string) =>
    `/api/school/trainings/${trainingId}/attendance/${athleteProfileId}`,
  athletePayments: (athleteProfileId: string) => `/api/school/athletes/${athleteProfileId}/payments`,
  athletePayment: (athleteProfileId: string, year: number, month: number) =>
    `/api/school/athletes/${athleteProfileId}/payments/${year}/${month}`,
  athleteReports: "/api/school/athlete-reports",
  athleteReport: (reportId: string) => `/api/school/athlete-reports/${reportId}`,
  schoolAthleteReports: (athleteProfileId: string) => `/api/school/athletes/${athleteProfileId}/reports`,
  meProfile: "/api/me/profile",
  meGroups: "/api/me/groups",
  meTrainings: "/api/me/trainings",
  meAttendance: "/api/me/attendance",
  mePayments: "/api/me/payments",
  meAthleteReports: "/api/me/athlete-reports"
} as const;
